### ISSUE TITLE
Missing description under title

### ISSUE THREAD

**Issue by naeemshaikh90** [lucamozza/LMArticleViewController#1]
![screen shot 2017-02-13 at 12 41 25 pm](https://cloud.githubusercontent.com/assets/10736853/22874036/ce9c8988-f1e9-11e6-8065-837e3b1750ea.png)

**Comment by lucamozza** [comment]
Added the description, thanks @naeemshaikh90

**Comment by naeemshaikh90** [comment]
#https://github.com/vsouza/awesome-ios/pull/1463
